// all the strings needed for converting numbers < 1000 into words
// 7 Feb 22 Richard Buckland

#define NAME0 "Zero"
#define NAME1 "One"
#define NAME2 "Two"
#define NAME3 "Three"
#define NAME4 "Four"
#define NAME5 "Five"
#define NAME6 "Six"
#define NAME7 "Seven"
#define NAME8 "Eight"
#define NAME9 "Nine"
#define NAME10 "Ten"
#define NAME11 "Eleven"
#define NAME12 "Twelve"
#define NAME13 "Thirteen"
#define NAME14 "Fourteen"
#define NAME15 "Fifteen"
#define NAME16 "Sixteen"
#define NAME17 "Seventeen"
#define NAME18 "Eighteen"
#define NAME19 "Nineteen"

#define NAME20 "Twenty"
#define NAME30 "Thirty"
#define NAME40 "Forty"
#define NAME50 "Fifty"
#define NAME60 "Sixty"
#define NAME70 "Seventy"
#define NAME80 "Eighty"
#define NAME90 "Ninety"

#define NAME100 "Hundred"

#define ANDJOIN " and "
